### Listar Usuários (Teste do GET)
GET http://korzelapi.somee.com/api/users
Accept: application/json

###

### Criar o Mestre Administrador (Teste do POST)
POST http://korzelapi.somee.com/api/users
Content-Type: application/json

{
  "username": "Varish",
  "email": "dinofalco123@gmail.com",
  "passwordHash": "Spectrovenator123",
  "role": 0
}


### Criar Ficha de Personagem (Teste)
POST http://korzelapi.somee.com/api/characters
Content-Type: application/json

{
  "userId": 1, 
  "name": "Kael, o Quebra-Marés",
  "race": "Korgath",
  "class": "Guerreiro",
  "level": 1,
  "vigor": 3,
  "agility": 0,
  "strength": 4,
  "intellect": -2,
  "instinct": 1,
  "presence": 0,
  "currentHP": 25,
  "maxHP": 25,
  "currentPE": 6,
  "maxPE": 6,
  "corruption": 0,
  "lascas": 1000,
  "baseDefense": 11
}

### Treinar o Kael em Atletismo
POST http://korzelapi.somee.com/api/characterskills
Content-Type: application/json

{
  "characterId": 1,
  "name": "Atletismo",
  "associatedAttribute": "Vigor",
  "isTrained": true,
  "miscBonus": 0
}

### Dar um Tridente de Guerra ao Kael
POST http://korzelapi.somee.com/api/characteritems
Content-Type: application/json

{
  "characterId": 1,
  "name": "Tridente de Guerra",
  "category": "Arma Exótica",
  "description": "Versátil (1d10). Não sofre penalidade na água. +2 para imobilizar.",
  "quantity": 1,
  "isEquipped": true,
  "damage": "1d8",
  "critical": "x2",
  "range": "6m",
  "damageType": "Perfurante",
  "defenseBonus": 0,
  "armorPenalty": 0
}

### Deletar a primeira duplicata (Atletismo ID 2)
DELETE http://korzelapi.somee.com/api/characterskills/2

### Deletar a segunda duplicata (Atletismo ID 3)
DELETE http://korzelapi.somee.com/api/characterskills/3

### Atualizar a ficha do Kael (Tomou 10 de dano)
PUT http://korzelapi.somee.com/api/characters/1
Content-Type: application/json

{
  "id": 1,
  "userId": 1,
  "name": "Kael, o Quebra-Marés",
  "race": "Korgath",
  "class": "Guerreiro",
  "level": 1,
  "vigor": 3,
  "agility": 0,
  "strength": 4,
  "intellect": -2,
  "instinct": 1,
  "presence": 0,
  "currentHP": 15,
  "maxHP": 25,
  "currentPE": 6,
  "maxPE": 6,
  "corruption": 0,
  "lascas": 1000,
  "baseDefense": 11
}